name: infra deploy

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  ARM_CLIENT_ID: "858ba5f5-62de-4041-a798-6bd94ddbf747"
  ARM_CLIENT_SECRET: ${{secrets.AZ_CLIENT_SECRET}}
  ARM_SUBSCRIPTION_ID: "f9ec3efc-a456-4f55-ac96-9bd4b39578a6"
  ARM_TENANT_ID: "3bd737dd-bc87-413a-a26d-b2336d2f90ce"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout git repo
        uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v2
        name: setup terraform

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - if: github.ref == 'refs/heads/master'
        name: Terraform Apply
        run: terraform apply -auto-approve
